

apiVersion: v1
kind: Pod
metadata:
  name: "$NAMESPACE-nfs-provisioner"
  labels:
    role: nfs-server
spec:
  containers:
  - name: nfs-server
    image: quay.io/openshifttest/nfs-server@sha256:4cc09ea24943bab91047845a53fb6afa3109fa9c4f25f97a2c8b49089056f2d3
    imagePullPolicy: IfNotPresent
    ports:
    - name: nfs
      containerPort: 2049
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: "/mnt/data"
      name: local
  volumes:
  - name: local
    emptyDir: {}
