
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tflannag-nfs
  labels:
    role: nfs-server
spec:
  storageClassName: sc-tflannag-nfs
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/"
    server: "$CLUSTER_IP"
  persistentVolumeReclaimPolicy: Delete
