apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-tflannag-nfs
parameters:
  archiveOnDelete: “false”
provisioner: example.com/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
